"""tabla_usuarios

Revision ID: 5084ea30081e
Revises: 
Create Date: 2023-01-30 22:14:53.820030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5084ea30081e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabla_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('nombre', sa.String(length=15), nullable=True),
    sa.Column('apellido', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tabla_usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tabla_usuarios_apellido'), ['apellido'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabla_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_tabla_usuarios_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabla_usuarios_password'), ['password'], unique=False)

    op.create_table('tabla_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(length=25), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('lugar', sa.String(length=25), nullable=True),
    sa.Column('direccion', sa.String(length=25), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('evento_presencial', sa.Integer(), nullable=True),
    sa.Column('fk_usuarios', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_usuarios'], ['tabla_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabla_eventos')
    with op.batch_alter_table('tabla_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tabla_usuarios_password'))
        batch_op.drop_index(batch_op.f('ix_tabla_usuarios_nombre'))
        batch_op.drop_index(batch_op.f('ix_tabla_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_tabla_usuarios_apellido'))

    op.drop_table('tabla_usuarios')
    # ### end Alembic commands ###
